FROM quay.io/keycloak/keycloak:23.0.7

ARG PLUGIN_VERSION=1.SNAPSHOT
ARG JAR_DIR=target/

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_SPI_THEME_ADMIN_DEFAULT=siop-2
ENV VCISSUER_WALTID_ADDRESS=http://localhost
ENV VCISSUER_WALTID_SIGNATORY_PORT=6001
ADD ${JAR_DIR}vc-issuer-${PLUGIN_VERSION}.jar /opt/keycloak/providers/vc-issuer-${PLUGIN_VERSION}.jar
