# # Stage 1: Build the application
# FROM maven:3.8.1 AS build
# WORKDIR /app
# COPY . .
# RUN mvn -q clean package

FROM busybox:1.36.0

ARG PLUGIN_VERSION=1.0.3
ARG JAR_DIR=target/

# we also need to add 3rd party dependencies
ADD ${JAR_DIR}lib/ /provider/
# COPY --from=build /app/${JAR_DIR}lib/ /provider
# typical context is the build-dir
ADD ${JAR_DIR}vc-issuer-${PLUGIN_VERSION}.jar /provider/vc-issuer.jar
# COPY --from=build /app/${JAR_DIR}vc-issuer-${PLUGIN_VERSION}.jar /provider/vc-issuer.jar

RUN mkdir /target

CMD ["cp", "-a",  "/provider/.", "/target/"]